---
title: "iMSMS_metagenomics_linear_regression"
author: "Daniel Hakim"
date: "1/18/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/dan_imsms") # Argh, Rmd files reference from current file but we want from one directory up.

DO_LINEAR_REGRESSION = TRUE
DO_ANCOM = FALSE
```

```{r}
# Convert abundance tsv files for new batch data to rda, only needs to be done once.
# Quote is funky in the import and export because some fool put an unterminated ' or " 
# into the woltka species names.  Need to disable check names or it will replace spaces with dots.
# taxa_new.list = list(
#  phylum = t(read.table(file='new_batch_data/phylum.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE)),
#  class = t(read.table(file='new_batch_data/class.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE)),
#  order = t(read.table(file='new_batch_data/order.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE)),
#  family = t(read.table(file='new_batch_data/family.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE)),
#  genus = t(read.table(file='new_batch_data/genus.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE)),
#  species = t(read.table(file='new_batch_data/species.tsv', sep='\t', quote="|", header=TRUE, row.names = 1, check.names=FALSE))
# )
# 
# save(taxa_new.list, file="rdata/taxa_new.list.rda")
# 
# seqmeta_extended = read.table(file='new_batch_data/iMSMS_phenotypes_for_Knight_Lab_20221104.txt', sep='\t', quote='|', header=TRUE, row.names=1, check.names=FALSE)
# 
# save(seqmeta_extended, file="rdata/seqmeta_extended.rda")
```

```{r}
source("scripts/linear_regression.R")
source("scripts/linear_regression_plot.R")
source("scripts/normalizeFunc.R")
```

```{r}
# load data for shotgun metagenomics analysis
load("rdata/seqmeta.rda") #meta data for 1152 samples
load("rdata/seqmeta_all.rda") #Qiita metadata including new round of samples
load("rdata/seqmeta_extended.rda") #Non Qiita metadata including new round of samples 
load("rdata/taxa.list.rda") # Raw abundance of metagenomics taxa, e.g. phylum, order, species
load("rdata/taxa_new.list.rda") # Raw abundance of new metagenomics taxa, "none" level

# Merge the extended data into seqmeta_all-we need both, then set row names to be the sample identifier
seqmeta_new = merge(seqmeta_all, seqmeta_extended,
                          by.x = "sample_name", by.y = 'row.names', all = TRUE)
rownames(seqmeta_new) = seqmeta_new$sample_name

# Match column names to the old data
seqmeta_new$iMSMS_ID = seqmeta_new$sample_name
seqmeta_new$age = as.numeric(seqmeta_new$host_age)
seqmeta_new$bmi = as.numeric(seqmeta_new$BMI)
seqmeta_new$site = as.factor(apply(seqmeta_new[c("iMSMS_ID")], 1, function(x){
  substr(x[[1]], 1, 3)
}))

seqmeta_new$treatment_status <- apply(
  seqmeta_new[c("disease", "Treatment_Status")], 1, function(row) {
    disease = row[[1]]
    treatment_status = row[[2]]

    if (disease == "MS" || disease == "MS (Unpaired)")
    {
      if (is.na(treatment_status) || treatment_status == "")
      {
        return("Untreated")
      }
      else if (treatment_status == "Treated")
        return("Treated")
      else if (treatment_status == "Off")
        return("Untreated")
      else
      {
        print(paste(c("Unknown Treatment Status for MS:", treatment_status)))
        return("Foobar")
      }
    }
    else if (disease == "Control")
      return("Control")
    else
    {
      print(paste(c("Unknown Disease value:", disease)))
      return("Foobar")
    }
  }
)
seqmeta_new$treatment_status = as.factor(unlist(seqmeta_new$treatment_status))

seqmeta_new$Collection_Site = as.factor(apply(seqmeta_new[c("Collection_Site")], 1, function(x){
  if (is.na(x))
    return(x)
  if (x == "SanSeb")
  {
    return("San Sebastian")
  }
  return(x)
}))


# Filter to only new samples
seqmeta_new = seqmeta_new[seqmeta_new$iMSMS_ID %in% colnames(taxa_new.list$species), ]

# clean up unused
rm(seqmeta_all)
rm(seqmeta_extended)
```

```{r}
# data filtering and normalization
use_dashes = function(data_table)
{
  for (x in 1:length(colnames(data_table)))
  {
    s = colnames(data_table)[x]
    colnames(data_table)[x] = paste(substring(s, 1, 5), substring(s, 7, 10), sep="-")
  }
  return(data_table)
}

preprocess <- function(inlist) {
  filtered = lapply(inlist,function(x){
    x = x[rowSums(x > 0) >= 0.05 * ncol(x), ]
    x = x[rowSums(x) > 10, ]
    x
  })
  rel = lapply(filtered, function(x){
    normalizeFunc(x, method = "relative")
  })
  ast = lapply(filtered, function(x){
    normalizeFunc(x, method = "AST")
  })
  return(list("filter"=filtered, "rel"=rel, "ast"=ast))
}

# filter the microbes (low abundance and prevalance)
# relative abundance
# Arcsine square-root transformation
taxa.list = lapply(taxa.list, use_dashes)
proc = preprocess(taxa.list)
taxa_old.list.filter = proc$filter
taxa_old.list.rel = proc$rel
taxa_old.list.ast = proc$ast

taxa_new.list = lapply(taxa_new.list, use_dashes)
proc2 = preprocess(taxa_new.list)
taxa_new.list.filter = proc2$filter
taxa_new.list.rel = proc2$rel
taxa_new.list.ast = proc2$ast
```

```{r}

# For each linear regression model, we need to define some subset of the data
# we wish to fit the model to, the fixed variable we want to learn about, 
# the levels of that fixed variable and whether to adjust at the household level
get_untreated_households = function(metadata)
{
  return (metadata[metadata$disease=="MS" & metadata$treatment_status == "Untreated" & metadata$age > 0 & metadata$bmi > 0, "household"])
}

get_treated_and_untreated_households = function(metadata)
{
  return (metadata[metadata$disease=="MS" & (metadata$treatment_status == "Untreated" | metadata$treatment_status == "Treated") & metadata$age > 0 & metadata$bmi > 0, "household"])
}

get_case_controls_of_households = function(metadata, households)
{
  return(metadata[(metadata$disease == "MS" | metadata$disease == "Control") & metadata$household %in% households,])
}

sample_households = function(households, ratio)
{
  num_households = length(households)
  return(sample(households, size=round(ratio * num_households)))
}

build_lr_tasks_all_MS_random_subset = function(data, metadata, suffix)
{
  lr_tasks = list()
  for (x in 1:10) {
    lr_tasks[[x]] = list(
      name=paste("MS_HHC", x, suffix, sep="_"),
      data=data,
      condition=get_case_controls_of_households(metadata, sample_households(get_treated_and_untreated_households(metadata), .5)),
      fixed.var1 = "disease",
      levels = c("Control", "MS"),
      house.adjust = F
    )
  }
  return(lr_tasks)
}

build_lr_tasks = function(data, metadata, suffix)
{
  # MS group (3 comparisons)
  lr_tasks = list(
    list(
      name=paste("MS_HHC", suffix, sep="_"),
      data=data,
      condition=get_case_controls_of_households(metadata, get_treated_and_untreated_households(metadata)),
      fixed.var1 = "disease",
      levels = c("Control", "MS"),
      house.adjust = F
    )
    #list(
    #  name=paste("UntreatedMS_HHC", suffix, sep="_"),
    #  data=data,
    #  condition=get_case_controls_of_households(metadata, get_untreated_households(metadata)),
    #  fixed.var1 = "disease",
    #  levels = c("Control", "MS"),
    #  house.adjust = F
    #),
    # list(
    #   name=paste("TreatedMS_HHC", suffix, sep="_"),
    #   data=data,
    #   condition=metadata[metadata$household %in% metadata[metadata$disease=="MS" & metadata$treatment_status == "Treated","household"],],
    #   fixed.var1 = "disease",
    #   levels = c("Control", "MS"),
    #   house.adjust = T
    # ),
    # list(
    #   name=paste("TreatedMS_UntreatedMS", suffix, sep="_"),
    #   data=data,
    #   condition = metadata[metadata$treatment_status != "Control", ],
    #   fixed.var1 = "treatment_status",
    #   levels = c("Untreated", "Treated"),
    #   house.adjust = F
    # )
  )
  return(lr_tasks)
}

lr_tasks_subsets_old = build_lr_tasks_all_MS_random_subset(taxa_old.list.rel, seqmeta, "old")
lr_tasks_subsets_new = build_lr_tasks_all_MS_random_subset(taxa_new.list.rel, seqmeta_new, "new")

lr_tasks_old = build_lr_tasks(taxa_old.list.rel, seqmeta, "old")
lr_tasks_new = build_lr_tasks(taxa_new.list.rel, seqmeta_new, "new")

ancom_tasks_old = build_lr_tasks(taxa_old.list.filter, seqmeta, "old")
ancom_tasks_new = build_lr_tasks(taxa_new.list.filter, seqmeta_new, "new")

lr_tasks = c(lr_tasks_old, lr_tasks_new)
ancom_tasks = c(ancom_tasks_old, ancom_tasks_new)

#lr_tasks = c(lr_tasks_new)
```

```{r}
source("scripts/linear_regression.R")

# Now perform the linear regression tasks
for (task in lr_tasks)
{
  if (!DO_LINEAR_REGRESSION)
    next
  name = task$name
  data = task$data
  condition = task$condition
  fixed.var1 = task$fixed.var1
  levels = task$levels
  house.adjust = task$house.adjust
  feature = "species"
  dir.out = "results/wol/linear_regression/"
  
  feature_data = data[[feature]]

  metares = linear_regression(
    rel.data = feature_data, 
    arcsin.transform =T, 
    filter =T, 
    fixed.var = c(fixed.var1, "sex", "age", "bmi"),
    levels =levels,
    house.adjust =house.adjust, 
    site =T, 
    condition =condition,
    taxa =feature, 
    out.file = paste(paste(dir.out, "/Linear_coefficient_metagenomics_Bootstrap", sep=""), feature, name, "_sex_age_bmi_fixed_house_site_random.xlsx",sep="_"))
  
  write.table(metares, file = paste(paste(dir.out, "tsv", sep=""), "/", name, "_bonferroni_Bootstrap.tsv", sep=""), row.names=FALSE, sep="\t")
}

```

```{r}

# if (!requireNamespace("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# BiocManager::install("ANCOMBC")
# BiocManager::install("phyloseq")
library(ANCOMBC)
library(phyloseq)
```


```{r}

for (task in ancom_tasks_old)
{
  if (!DO_ANCOM)
    next
  name = task$name
  data = task$data
  condition = task$condition
  fixed.var1 = task$fixed.var1
  levels = task$levels
  house.adjust = task$house.adjust
  feature = "species"
  dir.out = "results/wol/ancombc"
  feature_data = data[[feature]]

  shared = Reduce(intersect,list(colnames(feature_data),rownames(condition)))
  # print(length(shared))
  # print(length(colnames(feature_data)))
  # print(length(rownames(condition)))
  
  # Keep only the subset of samples in the subsetted metadata
  feature_data = feature_data[,shared]

  # Export data pre-ancom
  # write.csv(feature_data, paste(c("/Users/djhakim/dan_imsms/gibs_check/data_",name), collapse=""), row.names=TRUE)
  # write.csv(condition, paste(c("/Users/djhakim/dan_imsms/gibs_check/metadata_",name), collapse=""), row.names=TRUE)
  # print(paste(c(fixed.var1, "sex", "age", "bmi"), collapse=" + "))
  # print("household")
  
  
  OTU = otu_table(feature_data, taxa_are_rows = TRUE)
  META = sample_data(condition)
  TAX = NULL

  physeq = phyloseq(OTU, META, TAX)

  # output = ancombc2(data = physeq, assay_name = NULL, tax_level = NULL,
  #                   fix_formula = paste(c(fixed.var1, "sex", "age", "bmi"), collapse=" + "), rand_formula = "household",
  #                   p_adj_method = "holm")

  output = ancombc2(data = physeq, assay_name = NULL, tax_level = NULL,
                  fix_formula = paste(c(fixed.var1, "sex", "age", "bmi"), collapse=" + "), p_adj_method = "holm")

  
  print(output)
}
```
